#!/usr/bin/python

import socket
import time
 
network = 'mossad.voxanon.net'
port = 6667
irc = socket.socket ( socket.AF_INET, socket.SOCK_STREAM )
irc.connect ( ( network, port ) )
print irc.recv ( 4096 )
irc.send ( 'NICK scratchy\r\n' )
irc.send ( 'USER scratchy scratchy scratchy :Ohai\r\n' )
time.sleep(10)
irc.send ( 'JOIN #akira\r\n' )
irc.send ( 'PRIVMSG #akira :Hello World.\r\n' )
while True:
   data = irc.recv ( 4096 )
   if data.find ( 'PING' ) != -1:
      irc.send ( 'PONG ' + data.split() [ 1 ] + '\r\n' )
   if data.find ( '!scratchy quit' ) != -1:
      irc.send ( 'PRIVMSG #akira :Fine, if you dont want me\r\n' )
      irc.send ( 'QUIT\r\n' )
   if data.find ( 'hi scratchy' ) != -1:
      irc.send ( 'PRIVMSG #akira :I already said hi...\r\n' )
   if data.find ( 'hello scratchy' ) != -1:
      irc.send ( 'PRIVMSG #akira :I already said hi...\r\n' )
   if data.find ( 'KICK' ) != -1:
      irc.send ( 'JOIN #akira\r\n' )
   if data.find ( 'cheese' ) != -1:
      irc.send ( 'PRIVMSG #akira :WHERE!!!!!!\r\n' )
   if data.find ( 'slaps scratchy' ) != -1:
      irc.send ( 'PRIVMSG #akira :This is the Trout Protection Agency. Please put the Trout Down and walk away with your hands in the air.\r\n' )
   print data
